### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by patlefort** [manatools/dnfdaemon#20]
On Fedora 27, all up to date, tested on multiple systems. The dnfdaemon-system process just keep growing. It's at almost 800mb right now after about a day or 2.

**Comment by hcbd** [comment]
I can confirm this behaviour on (an up-to-date) Fedora 27.
dnfdaemon-system is using 1.4Gb of RAM on my system after running for several days.

**Comment by anaselli** [comment]
Could you please post how did you experienced it, which tests you made, commands for instance. I don't seem to have this issue on mageia.

**Comment by hcbd** [comment]
here is my usage of the software:
boot fedora:
I do nothing. 
Distrobution default settings start it up automaticly
the daemon uses about: 100-160Mb of RAM

one every day (or 2) i update my system via the commandline: dnf update
the GUI / dnfdragora i do not use (because the gui is not very intuitive or easy to use at all).
Almost every time I update the system via the commandline i get a notification from dnfdragora directly after the update saying that i need to update my system, which has just been done but it hasn't detected it yet.

After 30 min and 1 dnf update command (via cli) the memory usage of the dnfdeamon-system is 340MB

if i let run my system for several days; the daemon grows to 1.4Gb of RAM usage.
and most of the time i use the cli for a once a day update. 
and if i spot the daemon using massive amounts of RAM i will kill it via the system monitor or cli.

I also notice that when you rightclick the icon in the system tray (dnfdragora-updater) and hit 'check for updates' the dnfdaemon wiil grow in RAM with like a 100Mb. Should note that this doesn't always happen.

**Comment by anaselli** [comment]
> the GUI / dnfdragora i do not use (because the gui is not very intuitive or easy to use at all).
Well that's not true :p Maybe you're talking about dnfdragora-updater.

>Almost every time I update the system via the commandline i get a notification from dnfdragora 
> directly after the update saying that i need to update my system, which has just been done but it 
> hasn't detected it yet.
Maybe that is related to [dnfdragora issue 76](https://github.com/manatools/dnfdragora/issues/76) that i seem i cannot reproduce either. But mageia has not dnfdragora-updater yet.

> I also notice that when you rightclick the icon in the system tray (dnfdragora-updater) and hit 'check 
> for updates' the dnfdaemon wiil grow in RAM with like a 100Mb. Should note that this doesn't always 
> happen.
maybe it is related to dnfdragora-updater, maybe it does not close dnfdaemon connection well... i will invesigate that too.
btw which command are you using to check dnfdaemon memory usage?

**Comment by hcbd** [comment]
I use: Gnome's system monitor (https://wiki.gnome.org/Apps/SystemMonitor) because it comes with fedora as standard.

**Comment by anaselli** [comment]
@Conan-Kudo i think it is definitely a dnfdragora issue, it does not exit the daemon on quit, that was added to allow dnfdragora-updater going on... We need to find a better way

**Comment by anaselli** [comment]
I will do some tests in fedora to use either dnfdragora or dnfdragora-updater

**Comment by hcbd** [comment]
If I can make a suggestion.

the updater only needs the daemon every (depending on the settings) 180 minutes. Why not start the daemon when the updater needs it and closes it when the current command finishes. Hereby not using 100-160mb RAM of my systemresources for maybe 2 minutes of real usage each day.

And add a timeout function to the active connection(s) to the daemon, so they close if not used for x amount of time and not keep them open, when for example the applicationGUI crashes or locks up.

**Comment by anaselli** [comment]
Well the idea is that one... but updater was written by @besser82 so i need to check if that was wanted

**Comment by patlefort** [comment]
I installed a fresh Fedora 27 (Xfce spin) on a VM to be sure. I noticed that dnfdaemon-system only started when I opened dnfdragora-updater GUI and never closed it after. I let it run for a night and dnfdaemon-system is now at 590 mb.

**Comment by anaselli** [comment]
Yes the problem is right there. I'm on it.
