### ISSUE TITLE
Warnings from dnf for using deprecated APIs

### ISSUE THREAD

**Issue by genodeftest** [manatools/dnfdaemon#8]
When running yumex-dnf, I'm getting this warning a lot:

```
The 'group_persistor' function is not a part of DNF API and will be removed in the upcoming DNF release. Please use only officially supported API functions. DNF API documentation is available at https://dnf.readthedocs.org/en/latest/api.html.
```

**Comment by keithbowes** [comment]
I'm pretty sure this has long be fixed, so I'm not sure why the issue is still open. Plus, yumex is moving toward DNF5 and uses dnf5daemon-server when built to use DNF5 rather than the default DNF4. The new yumex sounds good, a package manager for not just RPMs, but I can't get it to work in Mageia 9 (it uses Python features added in Python 11, where Mageia 9 comes with Python 10, so all you get is an error); I know, I could use Cauldron, but the seemingly incessant updates really annoys me (I prefer a stable system with only occasional security updates and only do major updates when a new distro version is released every year or two; in fact, one thing I miss from Mandrake is the use of years as version numbers; I know Ubuntu still uses years as versions (like Ubuntu 24.04 means a release from April 2024), but Ubuntu is the suck (there's an "Ubuntu way" and they go out of their way to make sure that you can't use it your way; I've tried Ubuntu and I was so glad to go back to Mandrake/Mandriva/Mageia so I could use it the way I like it instead of the way that Ubuntu wants me to use it (if I wanted a company to have that much control over how I use my computer, I'd just use Windows))).

**Comment by genodeftest** [comment]
I don't use dnfdaemon any more and don't know whether the warning still happens or not, therefore I'm closing this very old issue. Please comment if you object or still see the issue nonetheless.
